---
title: "Paper #2, Table 1: Matched Comparison of Patients Undergoing ECPR Cannulation in ECMO Truck vs. MMRC Standard Protocol"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```
## Load Data

```{r load_data_packages}
library(tidyverse)

load("clean_data/data_imputed.RData")

# ECMO Truck Protocol: truck cohort, cannulated only
truck_ecpr <- data_imp %>%
  filter(cohort == "TR", ecmo_yn == 1)

# Standard MMRC ECPR Protocol: trlfmc cohort, cannulated only
standard_ecpr <- data_imp %>%
  filter(cohort == "trlfmc", ecmo_yn == 1)

# Combined for statistical tests
table_data <- data_imp %>%
  filter(cohort %in% c("TR", "trlfmc"), ecmo_yn == 1) %>%
  mutate(protocol = if_else(cohort == "TR", "Truck", "Standard"))

cat("ECMO Truck Protocol patients:", nrow(truck_ecpr), "\n")
cat("Standard MMRC ECPR Protocol patients:", nrow(standard_ecpr), "\n")
```

```{r helper_functions, echo=FALSE}
source("00_importfunctions.R")
```

## Table 3

```{r table3}
# Build table data frame
table3 <- data.frame(
  Variable = c(
    "Total Number",
    "",
    "Demographics",
    "Age, mean (SD)",
    "Sex, % male",
    "Race, % White",
    "Race, % African American",
    "",
    "Time Intervals",
    "9-1-1 call to ECMO cannulation hospital arrival time (min), mean (SD)",
    "Low flow time (min), mean (SD)",
    "Needle stick to ECMO time (min), mean (SD)",
    "",
    "Cardiac Arrest Characteristics",
    "VT/VF, n (%)",
    "Witnessed cardiac arrest, n (%)",
    "Bystander CPR, n (%)",
    "LUCAS placed, n (%)",
    "Intubated with ETT, n (%)",
    "Number of shocks, mean (SD)",
    "Lactate, mean (SD)",
    "pH, mean (SD)",
    "",
    "Outcomes",
    "Days on V-A ECMO, mean (SD)",
    "Hospital LOS (days), mean (SD)",
    "Survival to discharge, n (%)"
  ),

  Truck_ECPR = c(
    nrow(truck_ecpr),
    "",
    "",
    mean_sd(truck_ecpr$age),
    n_pct(truck_ecpr$sex, 1),
    n_pct(truck_ecpr$race, 1),
    n_pct(truck_ecpr$race, 2),
    "",
    "",
    mean_sd(truck_ecpr$call_to_cann_hosp_time),
    mean_sd(truck_ecpr$low_flow_time),
    mean_sd(truck_ecpr$ecmo_time),
    "",
    "",
    n_pct(truck_ecpr$init_rhythm, "VT/VF"),
    n_pct(truck_ecpr$witnessed, 1),
    n_pct(truck_ecpr$bystander_cpr, 1),
    n_pct(truck_ecpr$lucas, 1),
    n_pct(truck_ecpr$field_intubation, 1),
    mean_sd(truck_ecpr$n_shocks),
    mean_sd(truck_ecpr$lactate),
    mean_sd(truck_ecpr$ph),
    "",
    "",
    mean_sd(truck_ecpr$ecmo_days),
    mean_sd(truck_ecpr$los_days),
    n_pct(truck_ecpr$alive, 1)
  ),

  Standard_ECPR = c(
    nrow(standard_ecpr),
    "",
    "",
    mean_sd(standard_ecpr$age),
    n_pct(standard_ecpr$sex, 1),
    n_pct(standard_ecpr$race, 1),
    n_pct(standard_ecpr$race, 2),
    "",
    "",
    mean_sd(standard_ecpr$call_to_cann_hosp_time),
    mean_sd(standard_ecpr$low_flow_time),
    mean_sd(standard_ecpr$ecmo_time),
    "",
    "",
    n_pct(standard_ecpr$init_rhythm, "VT/VF"),
    n_pct(standard_ecpr$witnessed, 1),
    n_pct(standard_ecpr$bystander_cpr, 1),
    n_pct(standard_ecpr$lucas, 1),
    n_pct(standard_ecpr$field_intubation, 1),
    mean_sd(standard_ecpr$n_shocks),
    mean_sd(standard_ecpr$lactate),
    mean_sd(standard_ecpr$ph),
    "",
    "",
    mean_sd(standard_ecpr$ecmo_days),
    mean_sd(standard_ecpr$los_days),
    n_pct(standard_ecpr$alive, 1)
  ),

  P_Value = c(
    "--",
    "",
    "",
    format_pval(compare_continuous(truck_ecpr$age, standard_ecpr$age)),
    format_pval(compare_binary(table_data$sex, table_data$protocol)),
    format_pval(compare_binary(table_data$race == 1, table_data$protocol)),
    format_pval(compare_binary(table_data$race == 2, table_data$protocol)),
    "",
    "",
    format_pval(compare_continuous(truck_ecpr$call_to_cann_hosp_time, standard_ecpr$call_to_cann_hosp_time)),
    format_pval(compare_continuous(truck_ecpr$low_flow_time, standard_ecpr$low_flow_time)),
    format_pval(compare_continuous(truck_ecpr$ecmo_time, standard_ecpr$ecmo_time)),
    "",
    "",
    format_pval(compare_binary(table_data$init_rhythm == "VT/VF", table_data$protocol)),
    format_pval(compare_binary(table_data$witnessed, table_data$protocol)),
    format_pval(compare_binary(table_data$bystander_cpr, table_data$protocol)),
    format_pval(compare_binary(table_data$lucas, table_data$protocol)),
    format_pval(compare_binary(table_data$field_intubation, table_data$protocol)),
    format_pval(compare_continuous(truck_ecpr$n_shocks, standard_ecpr$n_shocks)),
    format_pval(compare_continuous(truck_ecpr$lactate, standard_ecpr$lactate)),
    format_pval(compare_continuous(truck_ecpr$ph, standard_ecpr$ph)),
    "",
    "",
    format_pval(compare_continuous(truck_ecpr$ecmo_days, standard_ecpr$ecmo_days)),
    format_pval(compare_continuous(truck_ecpr$los_days, standard_ecpr$los_days)),
    format_pval(compare_binary(table_data$alive, table_data$protocol))
  )
)

knitr::kable(table3, col.names = c("Variable", "ECMO Truck Protocol", "Standard MMRC ECPR Protocol", "P-Value"))
```

*Continuous variables compared using independent samples t-test (normally distributed) or Wilcoxon rank-sum test (non-normally distributed). Categorical variables compared using Fisher's exact test. Normality assessed via Shapiro-Wilk test.*

## Missingness Summary

```{r missingness, echo=FALSE}
# Show missingness for key variables
vars_of_interest <- c("age", "sex", "race", "call_to_cann_hosp_time",
                      "low_flow_time", "ecmo_time", "init_rhythm",
                      "witnessed", "bystander_cpr", "lucas", "field_intubation", "n_shocks",
                      "lactate", "ph", "ecmo_days", "los_days", "alive")

missingness <- data.frame(
  Variable = vars_of_interest,
  Truck_Missing = sapply(vars_of_interest, function(v) {
    if (v %in% names(truck_ecpr)) sum(is.na(truck_ecpr[[v]])) else NA
  }),
  Truck_Total = nrow(truck_ecpr),
  Standard_Missing = sapply(vars_of_interest, function(v) {
    if (v %in% names(standard_ecpr)) sum(is.na(standard_ecpr[[v]])) else NA
  }),
  Standard_Total = nrow(standard_ecpr)
)

rownames(missingness) <- NULL
missingness <- missingness %>%
  mutate(
    Truck_Pct = round(Truck_Missing / Truck_Total * 100, 1),
    Standard_Pct = round(Standard_Missing / Standard_Total * 100, 1)
  ) %>%
  select(Variable, Truck_Missing, Truck_Pct, Standard_Missing, Standard_Pct)

library(kableExtra)
knitr::kable(missingness,
             col.names = c("Variable", "Missing (n)", "Missing (%)", "Missing (n)", "Missing (%)")) %>%
  add_header_above(c(" " = 1, "ECMO Truck" = 2, "Standard ECPR" = 2))
```
